#ifndef _rc_h_
#define _rc_h_

namespace PeterDB {

#define ERR_FILE_NAME_EXISTS 1
#define ERR_FILE_CREATE_FAILED 2
#define ERR_FILE_NOT_EXISTS 3
#define ERR_FILE_DELETE_FAILED 4
#define ERR_FILE_HANDLE_REUSE 5
#define ERR_FILE_OPEN_FAILED 6
#define ERR_FILE_WRONG_FORMAT 7
#define ERR_FILE_CLOSE_FAILED 8

#define ERR_PAGE_READ_EXCEED 9
#define ERR_PAGE_WRITE_EXCEED 10
#define ERR_PAGE_BUFFER_INVALID 11

#define ERR_SLOT_READ_EXCEED 12

#define ERR_RECORD_DESCRIPTOR_EMPTY 13
#define ERR_RECORD_FROM_DATA_FAILED 14
#define ERR_RECORD_READ_DELETED 15
#define ERR_RECORD_DUPLICATE_DELETE 16

#define ERR_ATTRIBUTE_TYPE_UNDEFINED 17
#define ERR_ATTRIBUTE_NOT_EXISTS 18

#define ERR_CATALOG_NOT_EXISTS 19
#define ERR_CATALOG_ILLEGAL_DELETE 20
#define ERR_CATALOG_ILLEGAL_MODIFY 21

#define ERR_TABLE_NAME_EXISTS 22
#define ERR_TABLE_NOT_EXISTS 23

#define ERR_INDEX_UNMATCHED_TYPE 24
#define ERR_INDEX_INSERT_DUPLICATE 25
#define ERR_INDEX_DELETE_NOT_EXISTS 26
#define ERR_INDEX_FILE_NOT_EXISTS 27

}

#endif // _rc_h_
